name: Run Login Script

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "11 15 */3 * *"  # 每三天运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    retention-days: 3

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install-deps chromium
          playwright install chromium

      - name: 运行登录脚本
        env:
          RENEW_URL: ${{ secrets.RENEW_URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HEADER_SECRET: ${{ secrets.HEADER_SECRET }}
        run: python allow.py

      - name: Upload screenshot artifact
        # 如果你只想在失败时上传截图，可以取消注释下面这行
        # if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: '*.png'
