name: Run Login Script

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "11 15 * * 2"  # 每三天运行一次，可以根据需求调整时间
  push:
    branches:
      - main
jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install-deps chromium
          playwright install chromium

      - name: 运行登录脚本
        env:
          RENEW_URL: ${{ secrets.RENEW_URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python allow.py
